Allows ghost role static spawning
effigy-se/effigy-se pull request #519
Opened 2023-10-17 11:03 UTC by retlaw34

## About The Pull Request

Tin

![Screenshot_7736](https://github.com/effigy-se/effigy-se/assets/58402542/5cd89276-cc49-4eb8-aa09-85f13138f7d4)

## Why It's Good For The Game

This was shockingly easy 

## Changelog

:cl:
add: You can now spawn in as ghost roles as your selected character
/:cl:

2023-10-17 16:25 UTC, unit0016 commented
Two notes, one in code review form, another without.
First: Are ghostrole spawners prefs-equipped by *default*? There's a few roles that come to mind that'd be inappropriate to have it enabled on (caves skeleton, for instance) and I want to make sure there's a check for those in place. Can just be a var if it doesn't already exist.

2023-10-17 16:41 UTC, distributivgesetz requested changes

2023-10-17 16:41 UTC, distributivgesetz commented on local/code/modules/mob_spawn/mob_spawn.dm
> +#define GHOSTROLE_STATIC_APPEARANCE "Current"
undefine these

2023-10-17 16:41 UTC, distributivgesetz commented on local/code/modules/mob_spawn/mob_spawn.dm
> +/obj/effect/mob_spawn/ghost_role/
```suggestion
/obj/effect/mob_spawn/ghost_role
```

2023-10-17 16:41 UTC, distributivgesetz commented on local/code/modules/mob_spawn/mob_spawn.dm
> +	return spawned_mob
seconding ruby's thought, unmodularize this so we get a clear conflict

2023-10-17 17:23 UTC, lessthnthree commented on local/code/modules/mob_spawn/mob_spawn.dm
> +	var/mob/living/spawned_mob = new mob_type(get_turf(src)) //living mobs only
would this be a candidate to do in the style per effigy_proc.dm / local/local.md?
on a return false, could Do Things

2023-10-18 09:32 UTC, retlaw34 commented
> Two notes, one in code review form, another without. First: Are ghostrole spawners prefs-equipped by _default_? There's a few roles that come to mind that'd be inappropriate to have it enabled on (caves skeleton, for instance) and I want to make sure there's a check for those in place. Can just be a var if it doesn't already exist.

![image](https://github.com/effigy-se/effigy-se/assets/58402542/e3c71e25-d592-4491-b380-ee6deb6c4371)

Nope, it's disabled by default. The variables were actually already there, just unused.

2023-10-18 09:50 UTC, distributivgesetz requested changes

2023-10-18 09:50 UTC, distributivgesetz commented on local/code/modules/mob_spawn/mob_spawn.dm
> +	return spawned_mob
Remove this proc

2023-10-18 11:02 UTC, distributivgesetz approved these changes

2023-10-19 06:12 UTC, merged